# Generated by Django 4.1 on 2023-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi_check', '0003_alter_phone_info_reg_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_info',
            name='check_time',
            field=models.CharField(default=None, max_length=32, verbose_name='查询时间'),
        ),
    ]
