# Generated by Django 4.1 on 2023-06-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi_check', '0004_phone_info_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_info',
            name='reg_info',
            field=models.CharField(default=None, max_length=200, verbose_name='注册信息'),
        ),
    ]
